// External link (endpoints api)
export const BASE_URL_API = process.env.NEXT_PUBLIC_BASE_URL_API;

export const BASE_URL_API_V1 = BASE_URL_API + "/api/v1";

const Endpoints = {
  FILTER: {
    GET_LIST_DISTRIBUTOR: BASE_URL_API_V1 + "/distributor-filter-dms-v1/distributors",
    GET_LIST_PRODUCT: BASE_URL_API_V1 + "/product-filter-dms-v1/products",
    GET_LIST_PRODUCT_CATEGORIES: BASE_URL_API_V1 + "/product-filter/categories",
    GET_LIST_PRODUCT_INDUSTRIES: BASE_URL_API_V1 + "/product-filter/industries",
    PRODUCT_PROPERTIES: BASE_URL_API_V1 + "/product-filter/properties",
    PRODUCT_PROPERTIES_VALUE: BASE_URL_API_V1 + "/product-filter/property-values",
    ADMINISTRATIVE_REGIONS: BASE_URL_API_V1 + "/administrative-division/regions",
    CUSTOMER_TYPES: BASE_URL_API_V1 + "/customer-types",
    CHANNELS: BASE_URL_API_V1 + "/channels",
    PRODUCT_UNITS: BASE_URL_API_V1 + "/product-filter/units",
  },
  DOWNLOADED_FILE_LIST: BASE_URL_API_V1 + "/downloaded-files",
  REPORT: {
    FAVORITE_REPORT: BASE_URL_API_V1 + "/reports/favorites",
    SALE_REPORT: {
      SALE_REPORT_LIST: BASE_URL_API_V1 + "/reports/orders",
      ORDER_STATUS_REPORT: {
        ORDER_STATUS_REPORT_TABLE: BASE_URL_API_V1 + "/reports/orders/order-statuses",
        EXPORT_ORDER_STATUS_REPORT: BASE_URL_API_V1 + "/export-reports/orders/order-statuses",
        QUICK_VIEW_DATA: BASE_URL_API_V1 + "/quick-view-reports/orders/order-statuses",
      },
    },
    WAREHOUSE_REPORT: {
      WAREHOUSE_REPORT_LIST: BASE_URL_API_V1 + "/reports/warehouses",
      WAREHOUSE_TRANSACTION_REPORT: {
        WAREHOUSE_TRANSACTION_REPORT_TABLE: BASE_URL_API_V1 + "/reports/warehouses/transactions",
        EXPORT_WAREHOUSE_TRANSACTION_REPORT: BASE_URL_API_V1 + "/export-reports/warehouses/transactions",
        QUICK_VIEW_DATA: BASE_URL_API_V1 + "/quick-view-reports/warehouses/transactions",
      },
      WAREHOUSE_INVENTORY_REPORT: {
        WAREHOUSE_INVENTORY_REPORT_TABLE: BASE_URL_API_V1 + "/reports/warehouses/inventories",
        EXPORT_WAREHOUSE_INVENTORY_REPORT: BASE_URL_API_V1 + "/export-reports/warehouses/inventories",
        QUICK_VIEW_DATA: BASE_URL_API_V1 + "/quick-view-reports/warehouses/inventories",
      },
    },
    RAW_DATA: {
      EXPORT_RAW_DATA_REPORT: BASE_URL_API_V1 + "/export-reports/orders/raw-data",
    },
  },
  WAREHOUSE: {
    FILTER_WAREHOUSE: BASE_URL_API_V1 + "/warehouses/warehouses",
    GET_LIST_WAREHOUSE: BASE_URL_API_V1 + "/warehouses",
    LIST_WAREHOUSE_EXPORT: BASE_URL_API_V1 + "/exports/warehouses",
    UPDATE_STATUS: BASE_URL_API_V1 + "/warehouses/warehouse-statuses",
    LIST_INVENTORIES: BASE_URL_API_V1 + "/inventories",
    LIST_TRANSACTIONS_IMPORT: BASE_URL_API_V1 + "/warehouses/imports",
    LIST_TRANSACTIONS_AUDITS: BASE_URL_API_V1 + "/warehouses/audits",
    LIST_WAREHOUSE_ADJUSTMENTS: BASE_URL_API_V1 + "/warehouses/adjustments",
    LIST_WAREHOUSE_TRANSFER: BASE_URL_API_V1 + "/warehouses/transfers",
    SUB_ADDRESSES: BASE_URL_API_V1 + "/warehouses/addresses",
    WAREHOUSE_VOLATILITY: BASE_URL_API_V1 + "/warehouses/volatility",
    WAREHOUSE_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/summary",
    PRODUCT_LOG: BASE_URL_API_V1 + "/inventories/logs",
    UPDATE_MINIMUM_QUANTITY: BASE_URL_API_V1 + "/inventories/minimum-quantity",
    GET_CITY: BASE_URL_API_V1 + "/administrative-division/cities",
    GET_DISTRICT: BASE_URL_API_V1 + "/administrative-division/districts",
    GET_WARD: BASE_URL_API_V1 + "/administrative-division/wards",
    CREATE_WAREHOUSE_ADDRESS: BASE_URL_API_V1 + "/warehouse-addresses",
    LIST_INVENTORY_EXPORT: BASE_URL_API_V1 + "/exports/inventories",
    LIST_WAREHOUSE_TRANSACTION_EXPORT: BASE_URL_API_V1 + "/exports/warehouse-transactions",
    CREATE_TRANSACTION_IMPORT: BASE_URL_API_V1 + "/warehouse-transactions/imports",
    GET_DETAIL_TRANSACTION_ADJUSTMENT: BASE_URL_API_V1 + "/warehouse-transactions/products/adjustments",
    GET_DETAIL_TRANSACTION_INVENTORY: BASE_URL_API_V1 + "/warehouse-transactions/products/audits",
    CREATE_TRANSACTION_TRANSFER: BASE_URL_API_V1 + "/warehouse-transactions/transfers",
    CREATE_TRANSACTION_ADJUSTMENT: BASE_URL_API_V1 + "/warehouse-transactions/adjustments",
    CREATE_TRANSACTION_INVENTORY: BASE_URL_API_V1 + "/warehouse-transactions/audits",
    GET_PRODUCT_INVENTORY: BASE_URL_API_V1 + "/products/with-inventory",
    GET_DETAIL_IMPORT_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/products/imports",
    GET_DETAIL_TRANSFER_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/products/transfers",
    UPDATE_STATUS_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/status",
    UPDATE_STATUSES_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/statuses",
    DELETE_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions",
    GET_DETAIL_TRANSFER_WAREHOUSE_TRANSACTION: BASE_URL_API_V1 + "/warehouse-transactions/transfer/summary",
    UPLOAD_FILE: BASE_URL_API_V1 + "/upload-warehouse-transactions",
    GET_FILES: BASE_URL_API_V1 + "/warehouse-transactions/files",
  },
  PRODUCT: {
    BASE: BASE_URL_API_V1 + "/products",
    PRODUCT_CATEGORIES: BASE_URL_API_V1 + "/product-categories",
    PRODUCT_INDUSTRIES: BASE_URL_API_V1 + "/product-industries",
    PRODUCT_PROPERTIES: BASE_URL_API_V1 + "/product-properties",
    PRODUCT_PROPERTIES_VALUE: BASE_URL_API_V1 + "/product-properties/values",
    UPDATE_PRODUCT_PROPERTIES: BASE_URL_API_V1 + "/product-properties/products",
    UPDATE_PRODUCT_STATUSES: BASE_URL_API_V1 + "/products/statuses",
    UPLOAD_IMAGE_PRODUCT: BASE_URL_API_V1 + "/upload-products/images",
    PRODUCT_IMAGE: BASE_URL_API_V1 + "/product-images",
    THUMBNAIL_PRODUCT: BASE_URL_API_V1 + "/upload-products/thumbnail",
    DETAIL_PRODUCT: BASE_URL_API_V1 + "/products/detail",
    EXPORT_EXCEL_PRODUCT: BASE_URL_API_V1 + "/exports/products",
    PRODUCT_OTHER_INFORMATION: BASE_URL_API_V1 + "/product-other-infos",
    PRODUCT_UNIT: BASE_URL_API_V1 + "/product-units",
    PRODUCT_PRICE: BASE_URL_API_V1 + "/product-prices",
    UNITS: BASE_URL_API_V1 + "/units",
  },
};

export default Endpoints;
